<span class="boldtext">How do I add the thumbnails to my posts? </span>
<div class="indent">
  <p>Envisioned utilizes a script called TimThumb to automatically resize images. Whenever you make a new post you will need to add a custom field. Once you are on the edit/write page screen, click the "Screen Options" link on the top right of the screen and make sure "Custom Fields" is checked. Scroll down below the text editor and click on the &quot;custom fields&quot; link. In the &quot;Name&quot; section, input &quot;Thumbnail&quot; (this is case sensitive). In the &quot;Value&quot; area, input the url to your thumbnail image. Your image will automatically be resized and cropped. The image must be hosted on your domain. (this is to protect against bandwidth left) </p>
  <p><span class="style1">Important Note: You <u>must</u> CHMOD the &quot;cache&quot; folder located in the Envisioned directory to 777 for this script to work. You can CHMOD (change the permissions) of a file using your favorite FTP program. If you are confused try following <a href="http://www.siteground.com/tutorials/ftp/ftp_chmod.htm"><u>this tutorial</u></a><u>.</u> Of course instead of CHMODing the template folder (as in the tutorial) you would CHMOD the &quot;cache&quot; folder found within your theme's directory. </span></p>
</div>
<span class="boldtext">How do I add my title/logo? </span>
<div class="indent">
In this theme the title/logo is an image, which means you will need an image editor to add your own text. You can do this by opening the blank logo image located at Photoshop Files/logo_blank.png, or by opening the logo PSD file located at Photoshop Files/logo.psd. Replace the edited logo with the old logo by placing it in the following directory: theme/Envisioned/images, and naming the file "logo.png". If you need more room, or would like to edit the logo further, you can always do so by opening the original fully layered PSD file located at Photoshop Files/Envisioned.psd  </div>

<span class="boldtext"> How do I manage advertisements on my blog? </span>
<div class="indent">You can change the images used in each of the advertisements, as well as which URL each ad points to, through the custom option pages found in wp-admin. Once logged in to the wordpress admin panel, click &quot;Design&quot; and then &quot;Envisioned Theme Options&quot; to reveal the various theme options. You can also use the 125x125 advertisement widget by adding the ET: Advertisement widget to your sidebar, and filling in the required fields.  </div>

  <span class="boldtext">Creating a Gallery</span>
  <div class="indent">
  <p>Envisioned uses page templates to create its galleries. To create a new gallery, the first thing you will need to do is create a new page. After it as been created, locate the "Template" dropdown menu to the right of the WP Text Editor while editing your post. From this dropdown menu, select the "Portfolio" page template. Once selected, you will notice that a new settings box is loaded below the dropdown menu. This settings box is used to configure your new gallery. The portfolio works by aggregating a list of posts from a certain category (or combination of categories). Each post represents a single gallery item (which can be either a photo or a video).</p>
  <p>The "ET Page Templates Settings" box that appears after selecting the Portfolio page template gives you several options. Here you can choose to remove the sidebar from your page (by selected the "Full Width Page" box). You can choose to remove the Titles/Descriptions from each gallery item (by deselecting the "Show Titles/Descriptions" check boxes). You can also choose to allow the theme to automatically detect the orientation of each of your gallery photos. If the "Detect Portrait Images" option is selected, then all of your portrait image will be displayed in portrait mode in the gallery. If this option is not selected, then all posts will be cropped to a uniform landscape size. This looks a little nicer, but you sacrifice pieces of your portrait images when viewing the thumbnails in the gallery.</p>
  <p>Next you will need to define what actually shows up in your gallery. From within the settings box, locate the "Select gallery categories" section and check which categories you would like to include in your portfolio. When you select a category, every post from that category will show up as a thumbnail image on your gallery page.</p>
  <p>Now that your gallery has been populated with posts, the next step is to define a Photo and/or a Video for each. Edit one of the posts within your gallery category. When you edit your post, you will notice that some additional options have been added below the text editor. Here you can choose what type of post you are creating. If you are creating a "Photo" post, then check the "Photo" box. Next you will need to define an image for your post by adding the "Thumbnail" custom field as outlined in the "How do I add the thumbnails to my posts?" section above. If you would like to add a Video to the gallery item, then you would check "Video" instead. Then simply input the URL to your video in the "Video url" field below. The theme supports embedding videos from popular video hosts such as youtube. So if you wanted to embed this video (http://www.youtube.com/watch?v=kkGeOWYOFoA) then you would simply input that URL in the "Video url" field. Even if you are creating a Video post, you still need to add a Thumbnail custom field to create a thumbnail image for your video post.</p>
  </div>
  

  <span class="boldtext"> How do I set up the featured slider on the homepage? </span>
  <div class="indent">
  <p>The featured slider can be set up using two different methods. You can either popular the tabs using Pages, or you can popular it using posts from a designated category. In the Appearances > Envisioned Theme Options page in wp-admin, under the General Settings > Featured Slider tab, you will see an option that says "Use Pages." If you select this option then pages will be used, if you don't then posts will be used. If you want to use Pages then you simply select "Use Pages," and then below the option select which pages you would like to display in the slider. If you don't use pages, then simply select the "Featured Category" from the dropdown menu and posts from that category will be added to the slider. After you add content to the slider, you will need to add a Thumbnail image to each page/post as outlined in the "How do I add the thumbnails to my posts?" above. You can also add Video to each post as outlined in the "Adding video to your posts" section above.</p></div>
  
  
  <span class="boldtext"> How do I set up the two blurbs on the homepage, below the slider? </span>
  <div class="indent">
  <p>These blurbs are created using pages. Create two pages that you would like to use for these two blurbs, then go to the Appearances > Envisioned Theme Options page and click the General Settings > Homepage tab. Under the Content Area 1/2 dropdown menus, choose the two pages you would like to use. Within the pages you can use a "more" tag to truncate the post preview.
</p>
Next you will need to assign an Icon image to each blurb. This works just like Thumbnail images, except you use the custom field name "Icon" instead. So create a custom field for each page with the name of "Icon" and a value of the icon image you would like to use. Icons must not exceed 36x36 pixels to insure optimum display.
</div>

  <span class="boldtext"> How do I add a blog section? </span>
  <div class="indent">
  <p>To create a blog, all you need to do is create a new category and add posts to it. Because the theme uses Page Templates to create its galleries, the default category layout is already in blog-style mode. 
</p>
</div>